import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === 'production';
const distDir = 'dist';

// Ensure dist directory exists
fs.mkdirSync(distDir, { recursive: true });

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(distDir, 'main.js'),
	minify: prod,
});

if (prod) {
	await context.rebuild();

	// Copy manifest and styles to dist
	for (const file of ['manifest.json', 'styles.css']) {
		fs.copyFileSync(file, path.join(distDir, file));
		console.log(`Copied ${file} → ${distDir}/${file}`);
	}

	process.exit(0);
} else {
	// Dev mode: also copy on start
	for (const file of ['manifest.json', 'styles.css']) {
		if (fs.existsSync(file)) {
			fs.copyFileSync(file, path.join(distDir, file));
		}
	}
	await context.watch();
}
